HW is done
kirillgarbar/Arithm pull request #2
Opened 2021-04-27 14:56 UTC by kirillgarbar

Сделал всё кроме диаграммы. В реквест загрузил файлы с тестами, код на фшарпе и документацию

2021-04-29 07:40 UTC, gsvgit requested changes
Урлы странно выглядят (https://kirillgarbar.github.io/Arithm/)
Автоматически генерируемая документация по коду отсутсвует.
Описание структуры репозиторя отсутствует.
Ну и диаграмма.

Для описания языка можно и нужно использовать грамматику.

2021-04-29 07:40 UTC, gsvgit commented on README.md
> +Arithm is a tool which contains an interpreter for the simple programming language mainly designed to compute arithmetic expressions.
Не хотите уточнить про длинную арифметику?

2021-04-29 07:40 UTC, gsvgit commented on docsSrc/lang.md
> +RuFS uses simple programming language to define complex arithmetic expressions.
Таки Arithm или RuFS?

2021-04-29 07:40 UTC, gsvgit commented on src/Arithm/BigInt.fs
> +    let equalize (x, y) = // добавляет нули в начало одного из списков, пока их длина разная
А почеу бы не писать сразу нормальные комментарии, которые потом в документации отображаться будут?

2021-04-29 07:40 UTC, gsvgit commented on src/Arithm/BigInt.fs
> +    let equalize (x, y) = // добавляет нули в начало одного из списков, пока их длина разная
Это, естественно, не только этого места касается.

2021-04-29 07:40 UTC, gsvgit commented on README.md
> +Arithm is a tool which contains an interpreter for the simple programming language mainly designed to compute arithmetic expressions.
И почему шрифт такой огромный? Зачем?

2021-04-30 20:58 UTC, kirillgarbar commented
Диаграмма и описание структуры были третьим заданием, а его я (по крайней мере сейчас) решил не делать

2021-05-05 16:53 UTC, gsvgit commented
Ок, пусть пока без диаграмы)

2021-06-01 06:22 UTC, gsvgit commented
1) Всё ещё не вижу автогенерации документации по коду.
2) Кажется, Вы путаете структуру проекта и структуру репозитория. 
3) Вы примеры оформления смотрели?

2021-06-01 09:14 UTC, kirillgarbar commented
> 1. Всё ещё не вижу автогенерации документации по коду.
Я же спрашивал, можно ли руками написать
![image](https://user-images.githubusercontent.com/71129570/120297547-de644a00-c2d1-11eb-9430-68ded31d7261.png)

> 2. Кажется, Вы путаете структуру проекта и структуру репозитория.
Структура репозитория так выглядеть должна?
![image](https://user-images.githubusercontent.com/71129570/120298611-ebce0400-c2d2-11eb-82ce-821e0c788945.png)

> 3. Вы примеры оформления смотрели?
Пример оформления брал отсюда
![image](https://user-images.githubusercontent.com/71129570/120297954-487cef00-c2d2-11eb-866e-468a1fa39b70.png)
Благодарности, контрибьютинг и лицензию указывать смысла не вижу

2021-06-01 09:19 UTC, gsvgit commented
Кажется, я в ветках запутался. Вот здесь https://github.com/kirillgarbar/Arithm/tree/HWCheck (источник реквеста), структуры директории в ридми нету.

2021-06-01 09:33 UTC, kirillgarbar commented
> Кажется, я в ветках запутался. Вот здесь https://github.com/kirillgarbar/Arithm/tree/HWCheck (источник реквеста), структуры директории в ридми нету.

Так я же пример просто скинул, чтобы убедиться, правильно ли я понял, что нужно сделать

2021-06-01 09:38 UTC, gsvgit commented
А, ок. Да, тогда всё так. Я думал, это Вы мне показываете, что у Вас всё сделано, а я не вижу)

2021-06-01 17:50 UTC, kirillgarbar commented
> Это что за безобразие? Зачем вдруг менять синтаксис языка?
Возникла проблема с парсером, это было её самоё простое решение)

2021-06-01 18:03 UTC, gsvgit commented
А ещё проще вообще удалить парсер)

Не, это не дело.

On Tue, Jun 1, 2021, 8:50 PM Kirill ***@***.***> wrote:

> Это что за безобразие? Зачем вдруг менять синтаксис языка?
>
> Возникла проблема с парсером, это было её самоё простое решение)
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/kirillgarbar/Arithm/pull/2#issuecomment-852327153>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAA2CQGSY3XDPK6ORF4WGXDTQUMWHANCNFSM43VFHQXQ>
> .
>

2021-06-01 21:11 UTC, kirillgarbar commented
С парсером была беда, что не возникал парс еррор там, где следует, и я это поправил добавлением одной строчки в парсере. Насчёт репозитория - структуру репозитория я добавил, остальные замечания прокомментировал

2021-06-04 06:15 UTC, gsvgit approved these changes
Пойдёт. Хотя пример кода на языке можно бвло бы и в ридми указать, чтобы сразу понимать, что за калькулятор перед тобой.

2021-07-21 04:14 UTC, merged